name: Merge checks
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build all packages
        run: yarn build

      - name: E2E tests
        run: yarn test:end-to-end

      - name: Unit tests
        run: yarn test:unit-test

      - name: Formatting
        run: yarn test:prettier
