name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets
          # can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Create Release Pull Request --or-- Publish to npm
        uses: changesets/action@master
        with:
          publish: yarn pkgs:release
          version: yarn pkgs:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
